version: "3"
services:
    nginx:
        image: nginx:1.17.10
        container_name: ng01
        ports:
            - "80:80"
        volumes:
            - ./src:/src
            - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - web

    web:
        build: .
        container_name: dg01
        command: bash -c "
            python3 manage.py makemigrations && 
            python3 manage.py migrate && 
            gunicorn Moodie.wsgi:application -b 0:80"
        volumes:
            - ./src:/src


